name:                temperature-chart
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Werror
- -Widentities
- -Wmissing-export-lists
- -Wmissing-exported-signatures
- -Wpartial-fields
- -Wredundant-constraints

executables:
  temperature-chart-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - japanese-calendar
